export const manage_Actions= {
	manage_student :{
		NEW:"SHOW STUDENT",
		ADDSTUDENT:"ADD NEW STUDENT",
    POST:"LOGIN_ACCOUNT_POST",
		AUTHORIZED: "LOGIN_ACCOUNT_AURHORIZED",
		NOT_AUTHORIZED: "LOGIN_ACCOUNT_NOT_AUTHORIZED",
		FAILURE: "LOGIN_ACCOUNT_FAILURE"
	}
}


export const manage_Status ={
	manage_student :{
		NEW:"SHOW STUDENT",
		ADDSTUDENT:"ADD NEW STUDENT",
    AUTHORIZED: "LOGIN_ACCOUNT_AURHORIZED",
		NOT_AUTHORIZED: "LOGIN_ACCOUNT_NOT_AUTHORIZED",
		FAILURE: "LOGIN_ACCOUNT_FAILURE",
    LOADING:"LOGIN_ACCOUNT_LOADING"
	}


}
